# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29229f6647ee0d54cd0f19096d888ba75f4abbc1e92b2c15b1c66276360cabf24a8e0e3203eeac384571b2d4da298f0288bb26f9081137fd8cf6bf3959da2210

test:
  secret_key_base: 16d081dcb0c479960f5d91f1ab32c5154b60d1f2b1cfacb77640a7f8730b0a061e173890a4d03dfa4075b754fecc394810abed6c81b99ce95a7a97265d5aa2d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
